#!/usr/bin/env python3
"""Write the FP8 reference table from ml_dtypes.

The table lists every encoding of the four FP8 formats with the class, the
sign, and the value that ml_dtypes gives. Run the script from the repository
root:

    python -m venv .venv && .venv/bin/pip install ml_dtypes==0.6.0 numpy==2.5.3
    .venv/bin/python floaty-verify/scripts/generate_fp8_reference.py \
        > floaty-verify/data/fp8-reference.txt
"""

import sys

import ml_dtypes
import numpy as np

# floaty alias name, ml_dtypes type.
FORMATS = [
    ("F8E4M3", ml_dtypes.float8_e4m3fn),
    ("F8E5M2", ml_dtypes.float8_e5m2),
    ("F8E4M3Fnuz", ml_dtypes.float8_e4m3fnuz),
    ("F8E5M2Fnuz", ml_dtypes.float8_e5m2fnuz),
]


def classify(value: float, smallest_normal: float) -> str:
    if np.isnan(value):
        return "nan"
    if np.isinf(value):
        return "infinite"
    if value == 0:
        return "zero"
    if abs(value) < smallest_normal:
        return "subnormal"
    return "normal"


def main() -> None:
    out = sys.stdout
    out.write("# @generated by floaty-verify/scripts/generate_fp8_reference.py. Do not edit.\n")
    out.write(f"# ml_dtypes {ml_dtypes.__version__}, numpy {np.__version__}\n")
    out.write("# format <alias> <precision> <emax> <emin>\n")
    out.write("# <alias> <bits> <class> <sign> <value as float.hex, or nan>\n")
    for name, dtype in FORMATS:
        info = ml_dtypes.finfo(dtype)
        smallest_normal = float(info.smallest_normal)
        out.write(f"format {name} {info.nmant + 1} {info.maxexp - 1} {info.minexp}\n")
        values = np.arange(256, dtype=np.uint8).view(dtype).astype(np.float64)
        for bits, value in enumerate(values):
            value = float(value)
            kind = classify(value, smallest_normal)
            sign = "-" if np.signbit(value) else "+"
            text = "nan" if kind == "nan" else value.hex()
            out.write(f"{name} {bits:#04x} {kind} {sign} {text}\n")


if __name__ == "__main__":
    main()
