#!/usr/bin/env python3
"""Write the MX reference data from ml_dtypes.

The script writes three files into the directory that its argument names:

- mx-reference.txt lists every encoding of the MX formats FP4 E2M1, FP6
  E2M3, and FP6 E3M2 with the class, the sign, and the value that ml_dtypes
  gives, in the format of fp8-reference.txt.
- mx-from-f16.bin holds the MX encoding that ml_dtypes gives for every
  binary16 encoding, rounded to nearest even: 65536 bytes for each format, in
  the order of FORMATS.
- mx-arithmetic.bin holds the result that ml_dtypes gives for every operand
  pair of each format, in the order of FORMATS: `a + b`, `a - b`, `a * b`,
  and `a / b`, `n * n` bytes each at index `a * n + b` for a format of `n`
  encodings, then the square root of every operand, `n` bytes. ml_dtypes
  computes in binary32 and rounds to nearest even once more. Binary32 has
  more than twice the MX precision plus two bits, so the second rounding
  gives the correctly rounded result.

The MX formats have no infinity and no NaN. ml_dtypes gives the largest
finite value of its sign for an overflow and for an infinity, and a zero for
a NaN.

Run the script from the repository root:

    python -m venv .venv && .venv/bin/pip install ml_dtypes==0.6.0 numpy==2.5.3
    .venv/bin/python floaty-verify/scripts/generate_mx_reference.py floaty-verify/data
"""

import sys
import warnings
from pathlib import Path

import ml_dtypes
import numpy as np

# floaty alias name, ml_dtypes type, width in bits.
FORMATS = [
    ("F4E2M1Fn", ml_dtypes.float4_e2m1fn, 4),
    ("F6E2M3Fn", ml_dtypes.float6_e2m3fn, 6),
    ("F6E3M2Fn", ml_dtypes.float6_e3m2fn, 6),
]


def encodings(dtype, width: int) -> np.ndarray:
    """Return every encoding of a format as values of the format."""
    return np.arange(1 << width, dtype=np.uint8).view(dtype)


def classify(value: float, smallest_normal: float) -> str:
    if value == 0:
        return "zero"
    if abs(value) < smallest_normal:
        return "subnormal"
    return "normal"


def write_table(path: Path) -> None:
    lines = [
        "# @generated by floaty-verify/scripts/generate_mx_reference.py. Do not edit.",
        f"# ml_dtypes {ml_dtypes.__version__}, numpy {np.__version__}",
        "# format <alias> <precision> <emax> <emin>",
        "# <alias> <bits> <class> <sign> <value as float.hex>",
    ]
    for name, dtype, width in FORMATS:
        info = ml_dtypes.finfo(dtype)
        smallest_normal = float(info.smallest_normal)
        lines.append(f"format {name} {info.nmant + 1} {info.maxexp - 1} {info.minexp}")
        for bits, value in enumerate(encodings(dtype, width).astype(np.float64)):
            value = float(value)
            sign = "-" if np.signbit(value) else "+"
            lines.append(
                f"{name} {bits:#04x} {classify(value, smallest_normal)} {sign} {value.hex()}"
            )
    path.write_text("\n".join(lines) + "\n")


def write_conversions(path: Path) -> None:
    halves = np.arange(65536, dtype=np.uint32).astype(np.uint16).view(np.float16)
    with warnings.catch_warnings():
        # Overflow and NaN inputs are part of the table.
        warnings.simplefilter("ignore", RuntimeWarning)
        parts = [halves.astype(dtype).view(np.uint8).tobytes() for _, dtype, _ in FORMATS]
    path.write_bytes(b"".join(parts))


def write_arithmetic(path: Path) -> None:
    parts = []
    with warnings.catch_warnings():
        # Overflow and invalid results are part of the table.
        warnings.simplefilter("ignore", RuntimeWarning)
        for _, dtype, width in FORMATS:
            values = encodings(dtype, width)
            first, second = np.meshgrid(values, values, indexing="ij")
            for operation in (np.add, np.subtract, np.multiply, np.divide):
                parts.append(operation(first, second).astype(dtype).view(np.uint8).tobytes())
            parts.append(np.sqrt(values).astype(dtype).view(np.uint8).tobytes())
    path.write_bytes(b"".join(parts))


def main() -> None:
    directory = Path(sys.argv[1])
    write_table(directory / "mx-reference.txt")
    write_conversions(directory / "mx-from-f16.bin")
    write_arithmetic(directory / "mx-arithmetic.bin")


if __name__ == "__main__":
    main()
