#!/usr/bin/env python3
"""Write the FP8 reference data from ml_dtypes.

The script writes four files into the directory that its argument names:

- fp8-reference.txt lists every encoding of the four FP8 formats with the
  class, the sign, and the value that ml_dtypes gives.
- fp8-from-f16.bin holds the FP8 encoding that ml_dtypes gives for every
  binary16 encoding, rounded to nearest even: 65536 bytes for each format, in
  the order of FORMATS.
- fp8-arithmetic.bin holds the result that ml_dtypes gives for every operand
  pair of each format, in the order of FORMATS: `a + b`, `a - b`, `a * b`, and
  `a / b`, 65536 bytes each at index `a * 256 + b`, then the square root of
  every operand, 256 bytes. ml_dtypes computes in binary32 and rounds to
  nearest even once more. Binary32 has more than twice the FP8 precision plus
  two bits, so the second rounding gives the correctly rounded result.
- fp8-operations.bin holds, for each format in the order of FORMATS, the
  result that ml_dtypes gives for every operand: np.nextafter toward the
  largest value above it, then toward the smallest value below it, then
  np.negative, then np.abs, 256 bytes each; then np.copysign of every operand
  pair, 65536 bytes at index `a * 256 + b`. The targets of np.nextafter are
  the infinities, or the largest finite values of a format without an
  infinity.

Run the script from the repository root:

    python -m venv .venv && .venv/bin/pip install ml_dtypes==0.6.0 numpy==2.5.3
    .venv/bin/python floaty-verify/scripts/generate_fp8_reference.py floaty-verify/data
"""

import sys
import warnings
from pathlib import Path

import ml_dtypes
import numpy as np

# floaty alias name, ml_dtypes type.
FORMATS = [
    ("F8E4M3Fn", ml_dtypes.float8_e4m3fn),
    ("F8E5M2", ml_dtypes.float8_e5m2),
    ("F8E4M3Fnuz", ml_dtypes.float8_e4m3fnuz),
    ("F8E5M2Fnuz", ml_dtypes.float8_e5m2fnuz),
]


def classify(value: float, smallest_normal: float) -> str:
    if np.isnan(value):
        return "nan"
    if np.isinf(value):
        return "infinite"
    if value == 0:
        return "zero"
    if abs(value) < smallest_normal:
        return "subnormal"
    return "normal"


def write_table(path: Path) -> None:
    lines = [
        "# @generated by floaty-verify/scripts/generate_fp8_reference.py. Do not edit.",
        f"# ml_dtypes {ml_dtypes.__version__}, numpy {np.__version__}",
        "# format <alias> <precision> <emax> <emin>",
        "# <alias> <bits> <class> <sign> <value as float.hex, or nan>",
    ]
    for name, dtype in FORMATS:
        info = ml_dtypes.finfo(dtype)
        smallest_normal = float(info.smallest_normal)
        lines.append(f"format {name} {info.nmant + 1} {info.maxexp - 1} {info.minexp}")
        values = np.arange(256, dtype=np.uint8).view(dtype).astype(np.float64)
        for bits, value in enumerate(values):
            value = float(value)
            kind = classify(value, smallest_normal)
            sign = "-" if np.signbit(value) else "+"
            text = "nan" if kind == "nan" else value.hex()
            lines.append(f"{name} {bits:#04x} {kind} {sign} {text}")
    path.write_text("\n".join(lines) + "\n")


def write_conversions(path: Path) -> None:
    halves = np.arange(65536, dtype=np.uint32).astype(np.uint16).view(np.float16)
    with warnings.catch_warnings():
        # Overflow and NaN inputs are part of the table.
        warnings.simplefilter("ignore", RuntimeWarning)
        parts = [halves.astype(dtype).view(np.uint8).tobytes() for _, dtype in FORMATS]
    path.write_bytes(b"".join(parts))


def write_arithmetic(path: Path) -> None:
    parts = []
    with warnings.catch_warnings():
        # Overflow, invalid, and NaN results are part of the table.
        warnings.simplefilter("ignore", RuntimeWarning)
        for _, dtype in FORMATS:
            values = np.arange(256, dtype=np.uint8).view(dtype)
            first, second = np.meshgrid(values, values, indexing="ij")
            for operation in (np.add, np.subtract, np.multiply, np.divide):
                parts.append(operation(first, second).astype(dtype).view(np.uint8).tobytes())
            parts.append(np.sqrt(values).astype(dtype).view(np.uint8).tobytes())
    path.write_bytes(b"".join(parts))


def targets(dtype) -> tuple:
    """Return the values above and below every finite value of a format."""
    infinity = np.array([np.inf], dtype=np.float32).astype(dtype)
    if np.isinf(infinity[0]):
        largest = infinity
    else:
        largest = np.array([ml_dtypes.finfo(dtype).max], dtype=dtype)
    return np.repeat(largest, 256), np.repeat(-largest, 256)


def write_operations(path: Path) -> None:
    parts = []
    with warnings.catch_warnings():
        # NaN operands are part of the table.
        warnings.simplefilter("ignore", RuntimeWarning)
        for _, dtype in FORMATS:
            values = np.arange(256, dtype=np.uint8).view(dtype)
            above, below = targets(dtype)
            parts.append(np.nextafter(values, above).view(np.uint8).tobytes())
            parts.append(np.nextafter(values, below).view(np.uint8).tobytes())
            parts.append(np.negative(values).view(np.uint8).tobytes())
            parts.append(np.abs(values).view(np.uint8).tobytes())
            first, second = np.meshgrid(values, values, indexing="ij")
            parts.append(np.copysign(first, second).view(np.uint8).tobytes())
    path.write_bytes(b"".join(parts))


def main() -> None:
    directory = Path(sys.argv[1])
    write_table(directory / "fp8-reference.txt")
    write_conversions(directory / "fp8-from-f16.bin")
    write_arithmetic(directory / "fp8-arithmetic.bin")
    write_operations(directory / "fp8-operations.bin")


if __name__ == "__main__":
    main()
